name: Oplifesteal
version: '${project.version}'
main: me.otisps.oplifesteal.Oplifesteal
api-version: 1.18
authors: [ otisps ]
description: OP Enchanting Books dropped on death. Lifesteal. Player abolishment. Beacon revive.  Custom Crafting.
